=== BackupTheBerlios/partisipation-svn/trunk/gui/scn/scenario.dtd
<?xml encoding="UTF-8"?>

<!-- 
    SCRIPT: Document type definitions for the scenarios. 
    
    AUTHORS: Anton Huttenlocher, Oleksiy Reznikov

    NOTE: Please pay attention to the number, type, and order
          of parameters for each method call in your
          scenario files. They must conform to the
          GUI interface specification. This is NOT
          ensured by this DTD (i.e. a scenario that
          is completely valid against this DTD will
          fail at execution if you'll use a string value 
          where an integer does belong to according to
          the interface specification).
-->

<!-- Root element of a scenario -->
<!ELEMENT scenario (call+,expect?)*>
<!ATTLIST scenario name CDATA #IMPLIED>

<!-- Description of a single XML-RPC call to be sent -->
<!ELEMENT call (param*,sleep?,print?)>
<!ATTLIST call method CDATA #REQUIRED>

<!-- Parameter of a GUI method; heed the NOTE above! -->
<!ELEMENT param (#PCDATA)>

<!-- A message to be printed to the console -->
<!ELEMENT print (#PCDATA)>

<!-- Pause time in MILLISECONDS -->
<!ELEMENT sleep (#PCDATA)>

<!-- Expected reaction from GUI, i.e which core method
     shall the GUI call as response to the previous call
     and which parameter values ought be contained -->
<!ELEMENT expect (param*)>
<!ATTLIST expect method CDATA #REQUIRED>

=== BackupTheBerlios/partisipation-svn/trunk/gui/scn/scenarios/get.call_accept_other.side.terminates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scenario SYSTEM "../scenario.dtd">

<scenario name="Get call and other side terminates.">
<print>Please accept this call.</print>
<call method="incomingCall">
	<param>3</param>
	<param>123</param>
	<param>antoshka@iptel.org</param>
	<param>Anton Huttenlocher</param>
</call>
<expect method="acceptCall">
	<param>123</param>
</expect>
<sleep>500</sleep>
<call method="changeCallStatus">
	<param>123</param>
	<param>ACCEPTED</param>
</call>
<print>This call ought be active now.</print>
<sleep>10000</sleep>
<call method="changeCallStatus">
	<param>123</param>
	<param>TERMINATED</param>
</call>
<print>This call ought be terminated now.</print>
</scenario>

=== BackupTheBerlios/partisipation-svn/trunk/gui/scn/scenarios/test_incoming_call_accept.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scenario SYSTEM "../scenario.dtd">
<scenario name="Incoming Call">

	<call method="incomingCall">
		<param>1</param>
		<param>34527</param>
		<param>antoshka@iptel.org</param>
		<param>Mr. Anton Huttenlocher</param>
		<print>The GUI is going to show a dialog box now. Please ACCEPT this call.</print>
	</call>
	<expect method="acceptCall">
		<param>34527</param>
	</expect>

</scenario>

=== BackupTheBerlios/partisipation-svn/trunk/gui/scn/scenarios/make.call_other.side.terminates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scenario SYSTEM "../scenario.dtd">

<scenario name="Make call and other side terminates.">
<print>Please dial the number 123456789.</print>
<expect method="makeCall">
	<param>1</param>
	<param>123456789</param>
</expect>
<call method="changeCallStatus">
	<param>1</param>
	<param>TRYING</param>
</call>
<sleep>1000</sleep>
<call method="changeCallStatus">
	<param>1</param>
	<param>RINGING</param>
</call>
<sleep>5000</sleep>
<call method="changeCallStatus">
	<param>1</param>
	<param>CANCELLED</param>
</call>
<print>This call ought be terminated now.</print>
</scenario>

=== BackupTheBerlios/partisipation-svn/trunk/gui/scn/scenarios/get.call_accept_talk_hang.up.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scenario SYSTEM "../scenario.dtd">
<scenario name="Accept incoming call and hang up after a while.">

<print>Please accept this call.</print>
<call method="incomingCall">
		<param>1</param>
		<param>34527</param>
		<param>antoshka@iptel.org</param>
		<param>Mr. Anton Huttenlocher</param>
</call>
<expect method="acceptCall">
	<param>34527</param>
</expect>
<call method="changeCallStatus">
	<param>34527</param>
	<param>TRYING</param>
</call>
<sleep>1000</sleep>
<call method="changeCallStatus">
	<param>34527</param>
	<param>RINGING</param>
</call>
<sleep>5000</sleep>
<call method="changeCallStatus">
	<param>34527</param>
	<param>ACCEPTED</param>
</call>
<print>Please wait for a while and then terminated this call.</print>
<expect method="endCall">
	<param>34527</param>
</expect>
<sleep>3000</sleep>
<call method="changeCallStatus">
	<param>34527</param>
	<param>TERMINATED</param>
</call>
</scenario>

=== BackupTheBerlios/partisipation-svn/trunk/gui/scn/scenarios/make.call_other.side.accepts_change.speaker.volume_change.micro.volume.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scenario SYSTEM "../scenario.dtd">

<scenario name="Make call, other side accepts then change speaker and micro volume.">
<print>Please dial the number 123456789.</print>
<expect method="makeCall">
	<param>1</param>
	<param>123456789</param>
</expect>
<call method="changeCallStatus">
	<param>1</param>
	<param>TRYING</param>
</call>
<sleep>1000</sleep>
<call method="changeCallStatus">
	<param>1</param>
	<param>RINGING</param>
</call>
<sleep>5000</sleep>
<call method="changeCallStatus">
	<param>1</param>
	<param>ACCEPTED</param>
</call>
<call method="changeCallStatus">
	<param>1</param>
	<param>ACCEPTED</param>
</call>
<print>This call ought be active now.</print>
<sleep>5000</sleep>
<call method="setSpeakerVolume">
	<param>0.8</param>
</call>
<print>The speaker volume should be at 80% now.</print>
<sleep>5000</sleep>
<call method="setMicroVolume">
	<param>0.75</param>
</call>
<print>The micro volume should be at 75% now.</print>


</scenario>
