=== BackupTheBerlios/partisipation-svn/trunk/gui/cfg/gui_config.dtd
<!ELEMENT config (phonebook,remote)>

<!ELEMENT phonebook (entry)*>

<!ELEMENT remote (core,gui)>

<!ELEMENT entry EMPTY>
<!ATTLIST entry name CDATA #REQUIRED>
<!ATTLIST entry number CDATA #REQUIRED>

<!ELEMENT core EMPTY>
<!ATTLIST core host CDATA #REQUIRED>
<!ATTLIST core port CDATA #REQUIRED>

<!ELEMENT gui EMPTY>
<!ATTLIST gui host CDATA #REQUIRED>
<!ATTLIST gui port CDATA #REQUIRED>

=== BackupTheBerlios/partisipation-svn/trunk/gui/cfg/gui_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "gui_config.dtd">
<config>
	<phonebook>
		<entry name="Vladimir V. Putin" number="vovochka@kremlin.ru"/>
		<entry name="George W. Bush" number="george@whitehouse.gov"/>
		<entry name="Mickey Mouse" number="mickey@disneyland.com"/>
	</phonebook>
	<remote>
		<core host="192.168.0.1" port="7777"/>
		<gui host="192.168.0.1" port="8888"/>
	</remote>
</config>
